/*
    DOG breeds dict
    ================
*/
// Korean
var breedTranslateKR = 
{
    "affenpinscher" : "아펜핀셔",
    "african" : "아프리카니스",
    "airedale" : "에어데일 테리어",
    "akita" : "아키타견",
    "appenzeller" : "아펜젤러",
    "basenji" : "바센지",
    "beagle" : "비글",
    "bluetick" : "블루틱 쿤하운드",
    "borzoi" : "보르조이",
    "bouvier" : "보비에 드 플란더스",
    "boxer" : "복서",
    "brabancon" : "브라반숑",
    "briard" : "브리아드",
    "bulldog" : "불독",
    "bullterrier" : "불테리어",
    "cairn" : "케언 테리어",
    "cattledog" : "캐틀 독",
    "chihuahua" : "치와와",
    "chow" : "차우차우",
    "clumber" : "클럼버 스파니엘",
    "cockapoo" : "코카푸",
    "collie" : "콜리",
    "coonhound" : "쿤하운드",
    "corgi" : "웰시 코기",
    "cotondetulear" : "꼬똥 드 뚤레아",
    "dachshund" : "닥스훈드",
    "dalmatian" : "달마시안",
    "dane" : "그레이트 데인",
    "deerhound" : "디어하운드",
    "dhole" : "승냥이",
    "dingo" : "딩고",
    "doberman" : "도베르만",
    "elkhound" : "엘크하운드",
    "entlebucher" : "엔틀버쳐 마운틴 독",
    "eskimo" : "아메리칸 에스키모 독",
    "germanshepherd" : "저먼 셰퍼드",
    "greyhound" : "그레이하운드",
    "groenendael" : "그루넨달",
    "hound" : "하운드",
    "husky" : "허스키",
    "keeshond" : "키스훈드",
    "kelpie" : "오스트랄리안 캘피",
    "komondor" : "코몬도르",
    "kuvasz" : "쿠바스",
    "labrador" : "래브라도",
    "leonberg" : "레온베르거",
    "lhasa" : "라사 압소",
    "malamute" : "말라무트",
    "malinois" : "말라누아 (벨지언 셰퍼드 독)",
    "maltese" : "말티즈",
    "mastiff" : "마스티프",
    "mexicanhairless" : "멕시칸 헤어리스 독",
    "mix" : "믹스견",
    "mountain" : "마운틴 독",
    "newfoundland" : "뉴펀들랜드",
    "otterhound" : "오터 하운드",
    "papillon" : "빠삐용",
    "pekinese" : "페키니즈",
    "pembroke" : "웰시 코기 펨브로크",
    "pinscher" : "핀셔",
    "pointer" : "아크라이트 포인터",
    "pomeranian" : "포메라니안",
    "poodle" : "푸들",
    "pug" : "퍼그",
    "puggle" : "퍼글",
    "pyrenees" : "그레이트 피레니즈",
    "redbone" : "레드본 쿤하운드",
    "retriever" : "리트리버",
    "ridgeback" : "리지백",
    "rottweiler" : "로트와일러",
    "saluki" : "설루키",
    "samoyed" : "사모예드",
    "schipperke" : "스키퍼키",
    "schnauzer" : "슈나우저",
    "setter" : "세터",
    "sheepdog" : "쉽독",
    "shiba" : "시바견",
    "shihtzu" : "시츄",
    "spaniel" : "스파니엘",
    "springer" : "스프링어",
    "stbernard" : "세인트 버나드",
    "terrier" : "요크셔테리어",
    "vizsla" : "비즐라",
    "weimaraner" : "와이머라너",
    "whippet" : "휘핏",
    "wolfhound" : "아이리시 울프하운드",
    "frise" : "비숑 프리제"
};

// English
var breedTranslateEN = 
{
    "affenpinscher" : "Affen pinscher",
    "african" : "African",
    "airedale" : "Airedale",
    "akita" : "",
    "appenzeller" : "",
    "basenji" : "Basenji",
    "beagle" : "Beagle",
    "bluetick" : "",
    "borzoi" : "Borzoi",
    "bouvier" : "",
    "boxer" : "",
    "brabancon" : "",
    "briard" : "",
    "bulldog" : "Bulldog",
    "bullterrier" : "Bull-Terrier",
    "cairn" : "",
    "cattledog" : "",
    "chihuahua" : "Chihuahua",
    "chow" : "Chow",
    "clumber" : "",
    "cockapoo" : "",
    "collie" : "",
    "coonhound" : "",
    "corgi" : "Corgi",
    "cotondetulear" : "Coton de Tulear",
    "dachshund" : "Dachshünd",
    "dalmatian" : "Dalmatian",
    "dane" : "",
    "deerhound" : "Deer hound",
    "dhole" : "",
    "dingo" : "Dingo",
    "doberman" : "",
    "elkhound" : "Elk hound",
    "entlebucher" : "",
    "eskimo" : "Eskimo",
    "germanshepherd" : "German shepherd",
    "greyhound" : "Greyhound",
    "groenendael" : "",
    "hound" : "Hound",
    "husky" : "Husky",
    "keeshond" : "",
    "kelpie" : "",
    "komondor" : "",
    "kuvasz" : "",
    "labrador" : "",
    "leonberg" : "",
    "lhasa" : "",
    "malamute" : "Malamute",
    "malinois" : "",
    "maltese" : "Maltese",
    "mastiff" : "Mastiff",
    "mexicanhairless" : "",
    "mix" : "Mixed breed",
    "mountain" : "",
    "newfoundland" : "",
    "otterhound" : "",
    "papillon" : "",
    "pekinese" : "",
    "pembroke" : "",
    "pinscher" : "",
    "pointer" : "",
    "pomeranian" : "",
    "poodle" : "Poodle",
    "pug" : "Pug",
    "puggle" : "Puggle",
    "pyrenees" : "",
    "redbone" : "",
    "retriever" : "",
    "ridgeback" : "",
    "rottweiler" : "Rottweiler",
    "saluki" : "",
    "samoyed" : "Samoyed",
    "schipperke" : "",
    "schnauzer" : "Schnauzer",
    "setter" : "",
    "sheepdog" : "",
    "shiba" : "Shiba",
    "shihtzu" : "Shihtzu",
    "spaniel" : "Spaniel",
    "springer" : "",
    "stbernard" : "",
    "terrier" : "Yokshire Terrier",
    "vizsla" : "",
    "weimaraner" : "",
    "whippet" : "",
    "wolfhound" : ""
};